/* automatically generated from lightdm-gtk-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.4\"/><requires lib=\"greeter_menu_bar\" version=\"1.0\""
  "/><object class=\"GtkAccelGroup\" id=\"a11y_accelgroup\"/><object class"
  "=\"GtkAccelGroup\" id=\"power_accelgroup\"/><object class=\"GtkEventBox"
  "\" id=\"panel_window\"><property name=\"name\">panel_window</property><"
  "property name=\"visible\">True</property><property name=\"can_focus\">F"
  "alse</property><property name=\"valign\">start</property><child><object"
  " class=\"GreeterMenuBar\" id=\"menubar\"><property name=\"name\">menuba"
  "r</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"pack_direction\">rtl</prop"
  "erty><signal name=\"key-press-event\" handler=\"menubar_key_press_cb\" "
  "swapped=\"no\"/><child><object class=\"GtkMenuItem\" id=\"power_menuite"
  "m\"><property name=\"name\">power_menuitem</property><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><c"
  "hild type=\"submenu\"><object class=\"GtkMenu\" id=\"power_menu\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">False"
  "</property><property name=\"accel_group\">power_accelgroup</property><c"
  "hild><object class=\"GtkMenuItem\" id=\"suspend_menuitem\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\">Suspend</property><si"
  "gnal name=\"activate\" handler=\"suspend_cb\" swapped=\"no\"/></object>"
  "</child><child><object class=\"GtkMenuItem\" id=\"hibernate_menuitem\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">Hibernate"
  "</property><signal name=\"activate\" handler=\"hibernate_cb\" swapped=\""
  "no\"/></object></child><child><object class=\"GtkMenuItem\" id=\"restar"
  "t_menuitem\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">Restart...</property><signal name=\"activate\" handler=\"restart_cb\""
  " swapped=\"no\"/></object></child><child><object class=\"GtkMenuItem\" "
  "id=\"shutdown_menuitem\"><property name=\"use_action_appearance\">False"
  "</property><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"accel_path\">&lt;Login&gt;/"
  "power/shutdown</property><property name=\"label\" translatable=\"yes\">"
  "Shut Down...</property><signal name=\"activate\" handler=\"shutdown_cb\""
  " swapped=\"no\"/></object></child></object></child></object></child><ch"
  "ild><object class=\"GtkMenuItem\" id=\"a11y_menuitem\"><property name=\""
  "name\">a11y_menuitem</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><child type=\"submenu\">"
  "<object class=\"GtkMenu\" id=\"a11y_menu\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"accel_group\">a11y_accelgroup</property><child><object class=\"Gtk"
  "CheckMenuItem\" id=\"large_font_menuitem\"><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"accel_pat"
  "h\">&lt;Login&gt;/a11y/font</property><property name=\"label\" translat"
  "able=\"yes\">Large Font</property><signal name=\"toggled\" handler=\"a1"
  "1y_font_cb\" swapped=\"no\"/></object></child><child><object class=\"Gt"
  "kCheckMenuItem\" id=\"high_contrast_menuitem\"><property name=\"use_act"
  "ion_appearance\">False</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"accel"
  "_path\">&lt;Login&gt;/a11y/contrast</property><property name=\"label\" "
  "translatable=\"yes\">High Contrast</property><signal name=\"toggled\" h"
  "andler=\"a11y_contrast_cb\" swapped=\"no\"/></object></child><child><ob"
  "ject class=\"GtkCheckMenuItem\" id=\"keyboard_menuitem\"><property name"
  "=\"use_action_appearance\">False</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"accel_path\">&lt;Login&gt;/a11y/keyboard</property><property name="
  "\"label\" translatable=\"yes\">On Screen Keyboard</property><property n"
  "ame=\"use_underline\">True</property><signal name=\"toggled\" handler=\""
  "a11y_keyboard_cb\" swapped=\"no\"/></object></child><child><object clas"
  "s=\"GtkCheckMenuItem\" id=\"reader_menuitem\"><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"accel_"
  "path\">&lt;Login&gt;/a11y/reader</property><property name=\"label\" tra"
  "nslatable=\"yes\">Screen Reader</property><property name=\"use_underlin"
  "e\">True</property><signal name=\"toggled\" handler=\"a11y_reader_cb\" "
  "swapped=\"no\"/></object></child></object></child></object></child><chi"
  "ld><object class=\"GtkMenuItem\" id=\"language_menuitem\"><property nam"
  "e=\"name\">language_menuitem</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\">[language_code]</property><child type=\"submenu\"><object class"
  "=\"GtkMenu\" id=\"language_menu\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property></object></child></ob"
  "ject></child><child><object class=\"GtkMenuItem\" id=\"session_menuitem"
  "\"><property name=\"name\">session_menuitem</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "child type=\"submenu\"><object class=\"GtkMenu\" id=\"session_menu\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property></object></child></object></child><child><object class=\""
  "GtkMenuItem\" id=\"layout_menuitem\"><property name=\"name\">layout_men"
  "uitem</property><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"label\">[layout]</prop"
  "erty><child type=\"submenu\"><object class=\"GtkMenu\" id=\"layout_menu"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property></object></child></object></child><child><object cla"
  "ss=\"GtkSeparatorMenuItem\" id=\"clock_menuitem\"><property name=\"name"
  "\">clock_menuitem</property><property name=\"can_focus\">False</propert"
  "y></object></child><child><object class=\"GtkSeparatorMenuItem\" id=\"h"
  "ost_menuitem\"><property name=\"name\">host_menuitem</property><propert"
  "y name=\"can_focus\">False</property></object></child></object></child>"
  "<style><class name=\"background\"/></style></object><object class=\"Gtk"
  "EventBox\" id=\"power_window\"><property name=\"name\">power_window</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"ha"
  "lign\">center</property><property name=\"valign\">center</property><sig"
  "nal name=\"key-press-event\" handler=\"power_window_key_press_event_cb\""
  " swapped=\"no\"/><child><object class=\"GtkBox\" id=\"box3\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"orientation\">vertical</property><child><object "
  "class=\"GtkEventBox\" id=\"power_content_frame\"><property name=\"name\""
  ">content_frame</property><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><child><object class=\"GtkGrid"
  "\" id=\"grid2\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"margin_left\">24</prop"
  "erty><property name=\"margin_right\">24</property><property name=\"marg"
  "in_top\">24</property><property name=\"margin_bottom\">24</property><pr"
  "operty name=\"row_spacing\">6</property><property name=\"column_spacing"
  "\">6</property><child><object class=\"GtkImage\" id=\"power_icon\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"margin_left\">6</property><property name=\""
  "margin_right\">12</property><property name=\"margin_top\">6</property><"
  "property name=\"margin_bottom\">6</property><property name=\"stock\">gt"
  "k-missing-image</property></object><packing><property name=\"left_attac"
  "h\">0</property><property name=\"top_attach\">0</property><property nam"
  "e=\"height\">2</property></packing></child><child><object class=\"GtkLa"
  "bel\" id=\"power_title\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"halign\">star"
  "t</property><property name=\"margin_bottom\">6</property><property name"
  "=\"hexpand\">True</property><property name=\"label\">[title]</property>"
  "<attributes><attribute name=\"weight\" value=\"semibold\"/></attributes"
  "></object><packing><property name=\"left_attach\">1</property><property"
  " name=\"top_attach\">0</property></packing></child><child><object class"
  "=\"GtkLabel\" id=\"power_text\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"halign"
  "\">start</property><property name=\"hexpand\">True</property><property "
  "name=\"label\">[text]</property></object><packing><property name=\"left"
  "_attach\">1</property><property name=\"top_attach\">1</property></packi"
  "ng></child></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">0</property></packing></child><child><object class=\"GtkEv"
  "entBox\" id=\"power_buttonbox_frame\"><property name=\"name\">buttonbox"
  "_frame</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><child><object class=\"GtkButtonBox\" "
  "id=\"buttonbox1\"><property name=\"visible\">True</property><property n"
  "ame=\"can_focus\">False</property><property name=\"margin_left\">24</pr"
  "operty><property name=\"margin_right\">24</property><property name=\"ma"
  "rgin_top\">24</property><property name=\"margin_bottom\">24</property><"
  "property name=\"spacing\">6</property><property name=\"layout_style\">e"
  "nd</property><child><object class=\"GtkButton\" id=\"power_cancel_butto"
  "n\"><property name=\"label\" translatable=\"yes\">Cancel</property><pro"
  "perty name=\"name\">cancel_button</property><property name=\"visible\">"
  "True</property><property name=\"can_focus\">True</property><signal name"
  "=\"clicked\" handler=\"power_button_clicked_cb\" swapped=\"no\"/></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkButton\" id=\"power_ok_button\"><pro"
  "perty name=\"label\" translatable=\"yes\">OK</property><property name=\""
  "name\">power_ok_button</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><signal name=\"clicked\""
  " handler=\"power_button_clicked_cb\" swapped=\"no\"/></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">1</property></packing></child></o"
  "bject></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">True</property><property name=\"position\">1"
  "</property></packing></child></object></child><style><class name=\"back"
  "ground\"/></style></object><object class=\"GtkOverlay\" id=\"screen_ove"
  "rlay\"><property name=\"name\">screen</property><property name=\"can_fo"
  "cus\">False</property><property name=\"hexpand\">True</property><proper"
  "ty name=\"vexpand\">True</property><signal name=\"get-child-position\" "
  "handler=\"screen_overlay_get_child_position_cb\" swapped=\"no\"/><child"
  "><object class=\"GtkBox\" id=\"screen-child\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"orientation\">vertical</property><child><placeholder/></child></"
  "object></child><style><class name=\"lightdm-gtk-greeter\"/></style></ob"
  "ject><object class=\"GtkListStore\" id=\"user_liststore\"><columns><col"
  "umn type=\"gchararray\"/><column type=\"gchararray\"/><column type=\"gi"
  "nt\"/></columns></object><object class=\"GtkEventBox\" id=\"login_windo"
  "w\"><property name=\"name\">login_window</property><property name=\"vis"
  "ible\">True</property><property name=\"can_focus\">False</property><pro"
  "perty name=\"halign\">start</property><property name=\"valign\">start</"
  "property><child><object class=\"GtkBox\" id=\"login_box\"><property nam"
  "e=\"name\">login_box</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"orienta"
  "tion\">vertical</property><child><object class=\"GtkFrame\" id=\"conten"
  "t_frame\"><property name=\"name\">content_frame</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label_xalign\">0</property><property name=\"shadow_"
  "type\">none</property><child><object class=\"GtkGrid\" id=\"grid1\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"margin_left\">24</property><property name"
  "=\"margin_right\">24</property><property name=\"margin_top\">24</proper"
  "ty><property name=\"row_spacing\">6</property><property name=\"column_s"
  "pacing\">18</property><child><object class=\"GtkFrame\" id=\"user_image"
  "_border\"><property name=\"name\">user_image_border</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"halign\">center</property><property name=\"vali"
  "gn\">center</property><property name=\"label_xalign\">0</property><prop"
  "erty name=\"shadow_type\">none</property><child><object class=\"GtkImag"
  "e\" id=\"user_image\"><property name=\"name\">user_image</property><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"pixel_size\">80</property><property name=\""
  "icon_name\">avatar-default</property></object></child></object><packing"
  "><property name=\"left_attach\">0</property><property name=\"top_attach"
  "\">0</property><property name=\"height\">3</property></packing></child>"
  "<child><object class=\"GtkComboBox\" id=\"user_combobox\"><property nam"
  "e=\"name\">user_combobox</property><property name=\"width_request\">200"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"valign\">center</property><property name=\"margin_top\">12</property>"
  "<property name=\"hexpand\">True</property><property name=\"model\">user"
  "_liststore</property><signal name=\"changed\" handler=\"user_combobox_a"
  "ctive_changed_cb\" swapped=\"no\"/><signal name=\"key-press-event\" han"
  "dler=\"user_combo_key_press_cb\" swapped=\"no\"/><child><object class=\""
  "GtkCellRendererText\" id=\"cellrenderertext1\"/><attributes><attribute "
  "name=\"text\">1</attribute><attribute name=\"weight\">2</attribute></at"
  "tributes></child></object><packing><property name=\"left_attach\">1</pr"
  "operty><property name=\"top_attach\">0</property></packing></child><chi"
  "ld><object class=\"GtkEntry\" id=\"username_entry\"><property name=\"na"
  "me\">prompt_entry</property><property name=\"can_focus\">True</property"
  "><property name=\"hexpand\">True</property><property name=\"invisible_c"
  "har\">\342\200\242</property><property name=\"placeholder_text\" transl"
  "atable=\"yes\">Enter your username</property><signal name=\"focus-out-e"
  "vent\" handler=\"username_focus_out_cb\" swapped=\"no\"/><signal name=\""
  "key-press-event\" handler=\"username_key_press_cb\" swapped=\"no\"/></o"
  "bject><packing><property name=\"left_attach\">1</property><property nam"
  "e=\"top_attach\">1</property></packing></child><child><object class=\"G"
  "tkEntry\" id=\"password_entry\"><property name=\"name\">prompt_entry</p"
  "roperty><property name=\"width_request\">200</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"margin_bottom\">12</property><property name=\"hexpand\">"
  "True</property><property name=\"visibility\">False</property><property "
  "name=\"invisible_char\">\342\200\242</property><property name=\"primary"
  "_icon_activatable\">False</property><property name=\"secondary_icon_act"
  "ivatable\">False</property><property name=\"placeholder_text\" translat"
  "able=\"yes\">Enter your password</property><signal name=\"activate\" ha"
  "ndler=\"login_cb\" swapped=\"no\"/><signal name=\"key-press-event\" han"
  "dler=\"password_key_press_cb\" swapped=\"no\"/></object><packing><prope"
  "rty name=\"left_attach\">1</property><property name=\"top_attach\">2</p"
  "roperty></packing></child></object></child><child type=\"label_item\"><"
  "placeholder/></child></object><packing><property name=\"expand\">True</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">0</property></packing></child><child><object class=\"GtkInfoBar\" "
  "id=\"greeter_infobar\"><property name=\"name\">greeter_infobar</propert"
  "y><property name=\"can_focus\">False</property><child internal-child=\""
  "action_area\"><object class=\"GtkButtonBox\" id=\"infobar-action_area\""
  "><property name=\"can_focus\">False</property><property name=\"layout_s"
  "tyle\">end</property><child><placeholder/></child></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"position\">-1</property></packing></child><chi"
  "ld internal-child=\"content_area\"><object class=\"GtkBox\" id=\"infoba"
  "r-content_area\"><property name=\"can_focus\">False</property><child><o"
  "bject class=\"GtkLabel\" id=\"message_label\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" comments=\"This is a placeholder string and will be repl"
  "aced with a message from PAM\">[message]</property></object><packing><p"
  "roperty name=\"expand\">True</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">0</property></packing></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">-1</property></packin"
  "g></child></object><packing><property name=\"expand\">False</property><"
  "property name=\"fill\">True</property><property name=\"position\">1</pr"
  "operty></packing></child><child><object class=\"GtkFrame\" id=\"buttonb"
  "ox_frame\"><property name=\"name\">buttonbox_frame</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"label_xalign\">0</property><property name=\"shad"
  "ow_type\">none</property><child><object class=\"GtkBox\" id=\"box2\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"margin_left\">24</property><property nam"
  "e=\"margin_right\">24</property><property name=\"margin_bottom\">24</pr"
  "operty><child><object class=\"GtkButton\" id=\"cancel_button\"><propert"
  "y name=\"label\" translatable=\"yes\">Cancel</property><property name=\""
  "name\">cancel_button</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><signal name=\"clicked\" "
  "handler=\"cancel_cb\" swapped=\"no\"/></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">0</property></packing></child><child><object cla"
  "ss=\"GtkButton\" id=\"login_button\"><property name=\"label\" translata"
  "ble=\"yes\">Log In</property><property name=\"name\">login_button</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><signal name=\"clicked\" handler=\"login_cb\" swapp"
  "ed=\"no\"/></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"pack_type\">end"
  "</property><property name=\"position\">1</property></packing></child></"
  "object></child><child type=\"label_item\"><placeholder/></child></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">True</property><property name=\"position\">2</property></packing>"
  "</child></object></child><style><class name=\"background\"/></style></o"
  "bject></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 18636u;

