/* automatically generated from lightdm-bbqlinux-greeter.glade */
#ifdef __SUNPRO_C
#pragma align 4 (lightdm_gtk_greeter_ui)
#endif
#ifdef __GNUC__
static const char lightdm_gtk_greeter_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char lightdm_gtk_greeter_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kWindow\" id=\"login_window\"><property name=\"name\">login_window</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"res"
  "izable\">False</property><property name=\"decorated\">False</property><"
  "child><object class=\"GtkTable\" id=\"table1\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">26</property><property name=\"n_rows\">5</prope"
  "rty><property name=\"n_columns\">2</property><property name=\"column_sp"
  "acing\">18</property><property name=\"row_spacing\">6</property><child>"
  "<placeholder/></child><child><object class=\"GtkComboBox\" id=\"user_co"
  "mbobox\"><property name=\"name\">user_combobox</property><property name"
  "=\"width_request\">200</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"model\">user_liststore</property><signal name=\""
  "changed\" handler=\"user_combobox_active_changed_cb\" swapped=\"no\"/><"
  "signal name=\"key-press-event\" handler=\"user_combobox_key_press_cb\" "
  "swapped=\"no\"/></object><packing><property name=\"left_attach\">1</pro"
  "perty><property name=\"right_attach\">2</property><property name=\"y_op"
  "tions\"/></packing></child><child><object class=\"GtkEntry\" id=\"passw"
  "ord_entry\"><property name=\"name\">prompt_entry</property><property na"
  "me=\"width_request\">200</property><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">True</property><property name=\"invi"
  "sible_char\">\342\200\242</property><property name=\"invisible_char_set"
  "\">True</property><property name=\"primary_icon_activatable\">False</pr"
  "operty><property name=\"secondary_icon_activatable\">False</property><s"
  "ignal name=\"activate\" handler=\"login_cb\" swapped=\"no\"/></object><"
  "packing><property name=\"left_attach\">1</property><property name=\"rig"
  "ht_attach\">2</property><property name=\"top_attach\">2</property><prop"
  "erty name=\"bottom_attach\">3</property><property name=\"y_options\"/><"
  "/packing></child><child><object class=\"GtkImage\" id=\"user_image\"><p"
  "roperty name=\"name\">user_image</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"pixel_size\">80</property><property name=\"icon_name\">avatar-defa"
  "ult</property></object><packing><property name=\"bottom_attach\">3</pro"
  "perty><property name=\"x_options\"/><property name=\"y_options\"/></pac"
  "king></child><child><object class=\"GtkLabel\" id=\"message_label\"><pr"
  "operty name=\"name\">message_label</property><property name=\"can_focus"
  "\">False</property><property name=\"label\" comments=\"This is a placeh"
  "older string and will be replaced with a message from PAM\">[message]</"
  "property></object><packing><property name=\"right_attach\">2</property>"
  "<property name=\"top_attach\">3</property><property name=\"bottom_attac"
  "h\">4</property></packing></child><child><object class=\"GtkHBox\" id=\""
  "hbox2\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><child><object class=\"GtkButton\" id=\"login_b"
  "utton\"><property name=\"name\">login_button</property><property name=\""
  "label\" translatable=\"yes\">Log In</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">True</property><signal name=\"key-press-event\""
  " handler=\"login_button_key_press_cb\" swapped=\"no\"/><signal name=\"c"
  "licked\" handler=\"login_cb\" swapped=\"no\"/></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"pack_type\">end</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkButton\" id="
  "\"cancel_button\"><property name=\"name\">cancel_button</property><prop"
  "erty name=\"label\" translatable=\"yes\">Cancel</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">True</property><signal name=\"cli"
  "cked\" handler=\"cancel_cb\" swapped=\"no\"/></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">True</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"left_attach\">1</property><property name=\"righ"
  "t_attach\">2</property><property name=\"top_attach\">4</property><prope"
  "rty name=\"bottom_attach\">5</property></packing></child><child><object"
  " class=\"GtkEntry\" id=\"username_entry\"><property name=\"name\">promp"
  "t_entry</property><property name=\"can_focus\">True</property><property"
  " name=\"no_show_all\">True</property><property name=\"invisible_char\">"
  "\342\200\242</property><signal name=\"key-press-event\" handler=\"usern"
  "ame_key_press_cb\" swapped=\"no\"/><signal name=\"focus-out-event\" han"
  "dler=\"username_focus_out_cb\" swapped=\"no\"/></object><packing><prope"
  "rty name=\"left_attach\">1</property><property name=\"right_attach\">2<"
  "/property><property name=\"top_attach\">1</property><property name=\"bo"
  "ttom_attach\">2</property></packing></child></object></child></object><"
  "object class=\"GtkWindow\" id=\"panel_window\"><property name=\"name\">"
  "panel_window</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"decorated\">False</property><child><object class=\"GtkHBu"
  "ttonBox\" id=\"buttonbox1\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><child><object class=\"GtkL"
  "abel\" id=\"hostname_label\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"xalign\">"
  "0</property><property name=\"xpad\">6</property><property name=\"label\""
  ">[hostname]</property></object><packing><property name=\"expand\">False"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">0</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"clock_label\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\">label</property></object><packing><property name=\"expand\">F"
  "alse</property><property name=\"fill\">True</property><property name=\""
  "pack_type\">end</property><property name=\"position\">1</property></pac"
  "king></child><child><object class=\"GtkMenuBar\" id=\"menubar\"><proper"
  "ty name=\"name\">panel_window</property><property name=\"visible\">True"
  "</property><property name=\"can_focus\">True</property><property name=\""
  "take_focus\">True</property><property name=\"pack_direction\">rtl</prop"
  "erty><signal name=\"key-press-event\" handler=\"menubar_key_press_cb\" "
  "swapped=\"no\"/><child><object class=\"GtkMenuItem\" id=\"power_menuite"
  "m\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">True</property><child type=\"submenu\"><object class=\"GtkMenu\" id"
  "=\"power_menu\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><child><object class=\"GtkMenuItem\" id"
  "=\"suspend_menuitem\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">Suspend</property><signal name=\"activate\" handler=\"susp"
  "end_cb\" swapped=\"no\"/></object></child><child><object class=\"GtkMen"
  "uItem\" id=\"hibernate_menuitem\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">Hibernate</property><signal name=\"activate\" "
  "handler=\"hibernate_cb\" swapped=\"no\"/></object></child><child><objec"
  "t class=\"GtkMenuItem\" id=\"restart_menuitem\"><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">False</property><proper"
  "ty name=\"label\" translatable=\"yes\">Restart...</property><signal nam"
  "e=\"activate\" handler=\"restart_cb\" swapped=\"no\"/></object></child>"
  "<child><object class=\"GtkMenuItem\" id=\"shutdown_menuitem\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"label\" translatable=\"yes\">Shut Down...</prop"
  "erty><signal name=\"activate\" handler=\"shutdown_cb\" swapped=\"no\"/>"
  "</object></child></object></child></object></child><child><object class"
  "=\"GtkMenuItem\" id=\"a11y_menuitem\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><child type=\"subm"
  "enu\"><object class=\"GtkMenu\" id=\"a11y_menu\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><child"
  "><object class=\"GtkCheckMenuItem\" id=\"large_font_menuitem\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"label\" translatable=\"yes\">Large Font</prope"
  "rty><signal name=\"toggled\" handler=\"a11y_font_cb\" swapped=\"no\"/><"
  "/object></child><child><object class=\"GtkCheckMenuItem\" id=\"high_con"
  "trast_menuitem\"><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">False</property><property name=\"label\" translatable="
  "\"yes\">High Contrast</property><signal name=\"toggled\" handler=\"a11y"
  "_contrast_cb\" swapped=\"no\"/></object></child><child><object class=\""
  "GtkCheckMenuItem\" id=\"keyboard_menuitem\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label\" translatable=\"yes\">On Screen Keyboard</property><proper"
  "ty name=\"use_underline\">True</property><signal name=\"toggled\" handl"
  "er=\"a11y_keyboard_cb\" swapped=\"no\"/></object></child></object></chi"
  "ld></object></child><child><object class=\"GtkMenuItem\" id=\"language_"
  "menuitem\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><child type=\"submenu\"><object class=\"GtkMe"
  "nu\" id=\"language_menu\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property></object></child></object></c"
  "hild><child><object class=\"GtkMenuItem\" id=\"session_menuitem\"><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><child type=\"submenu\"><object class=\"GtkMenu\" id=\"sessio"
  "n_menu\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property></object></child></object></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"pack_type\">end</property><property na"
  "me=\"position\">2</property></packing></child></object></child></object"
  "><object class=\"GtkListStore\" id=\"user_liststore\"><columns><column "
  "type=\"gchararray\"/><column type=\"gchararray\"/><column type=\"gint\""
  "/></columns></object></interface>"
};

static const unsigned lightdm_gtk_greeter_ui_length = 9912u;

